### ISSUE TITLE
Mention that it should not be used in official capacity

### ISSUE THREAD

**Issue by ewjoachim** [jperelli/eucovidcert#1]
Congratulations on building this app so quickly !

I'm slightly worried that people might be tempted to use it in real scenarii in lieu of official apps, and if there's no signature check, this could create a risk. Do you think it would make sense to add a warning in the app that it's not to be used to check the validity of real certs for events, but just for people curious to know what their qr code contains ?

**Comment by jperelli** [comment]
Sure, will do now! thanks for the heads up!

**Comment by ewjoachim** [comment]
Thank you :)
